### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'makeRandom')

### ISSUE THREAD

**Issue by spraveenitpro** [bitcoinjs/ecpair#7] opened 2022-04-13 04:51 UTC
Hi There,

I am currently running this code that generates a public address and its private key:

```
'use strict'; 
module.exports = function create_btc_address(){ 
const  bitcoin =require('bitcoinjs-lib');
const {  Signer, SignerAsync, ECPairInterface, ECPair } = require('ecpair'); 
  const TESTNET = bitcoin.networks.testnet;
  const keyPair = ECPair.makeRandom({ network: TESTNET });
const { address } = bitcoin.payments.p2pkh({
 pubkey: keyPair.publicKey,
 network: TESTNET,
 });
 const privateKey = keyPair.toWIF();
console.log(address+" "+privateKey);
}

```

Upon running this with node I am getting:

```
TypeError: Cannot read properties of undefined (reading 'makeRandom')
```

I am on the below versions of node and npm:

node v16.13.2
npm 8.6.0

Any idea on what I could be missing in this case?

Thanks

**Comment by junderw** [comment] 2022-04-13 06:54
Read the README.

This is the exact same issue as bip32. You are not reading the README. Closing as duplicate of https://github.com/bitcoinjs/bip32/issues/61

**Closed by junderw** 2022-04-13 06:54 UTC

**Comment by junderw** [comment] 2022-04-13 06:55
hint: look at `ECPairFactory ` what does it do.

**Comment by ShenTD** [comment] 2023-10-18 15:39
> Thank you for your explanation, I got it to work, pretty new to this. Really Appreciate!!

@spraveenitpro I meet the same questio. How do you solve it? Can you show me the code , example. or url. The ts example in README is hard to me.
